# Generated by Django 4.1.3 on 2022-11-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
